# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formMonsterDB.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt4.QtGui import *


class Frame_New_Monster(QFrame):
    def __init__(self, parent=None):
        super(Frame_New_Monster, self).__init__(parent)
        self.setObjectName("FormMonsterInput")
        self.resize(981, 580)
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.nomeLabel = QLabel(self)
        self.nomeLabel.setObjectName("nomeLabel")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.nomeLabel)
        self.nomeLineEdit = QLineEdit(self)
        self.nomeLineEdit.setObjectName("nomeLineEdit")
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.nomeLineEdit)
        self.iniziativaLabel = QLabel(self)
        self.iniziativaLabel.setObjectName("iniziativaLabel")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.iniziativaLabel)
        self.iniziativaLineEdit = QLineEdit(self)
        self.iniziativaLineEdit.setObjectName("iniziativaLineEdit")
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.iniziativaLineEdit)
        self.pELabel = QLabel(self)
        self.pELabel.setObjectName("pELabel")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.pELabel)
        self.pELineEdit = QLineEdit(self)
        self.pELineEdit.setObjectName("pELineEdit")
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.pELineEdit)
        self.tesoroButton = QPushButton(self)
        self.tesoroButton.setObjectName("tesoroButton")
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.tesoroButton)
        self.tesoroLineEdit = QLineEdit(self)
        self.tesoroLineEdit.setObjectName("tesoroLineEdit")
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.tesoroLineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_3 = QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.allineamentoLineEdit = QLineEdit(self)
        self.allineamentoLineEdit.setObjectName("allineamentoLineEdit")
        self.formLayout_3.setWidget(1, QFormLayout.FieldRole, self.allineamentoLineEdit)
        self.categoriaLabel = QLabel(self)
        self.categoriaLabel.setObjectName("categoriaLabel")
        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.categoriaLabel)
        self.categoriaLineEdit = QLineEdit(self)
        self.categoriaLineEdit.setObjectName("categoriaLineEdit")
        self.formLayout_3.setWidget(2, QFormLayout.FieldRole, self.categoriaLineEdit)
        self.auraLabel = QLabel(self)
        self.auraLabel.setObjectName("auraLabel")
        self.formLayout_3.setWidget(3, QFormLayout.LabelRole, self.auraLabel)
        self.auraLineEdit = QLineEdit(self)
        self.auraLineEdit.setObjectName("auraLineEdit")
        self.formLayout_3.setWidget(3, QFormLayout.FieldRole, self.auraLineEdit)
        self.allineamentoLabel = QLabel(self)
        self.allineamentoLabel.setObjectName("allineamentoLabel")
        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.allineamentoLabel)
        self.gSLineEdit = QLineEdit(self)
        self.gSLineEdit.setObjectName("gSLineEdit")
        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.gSLineEdit)
        self.gSLabel = QLabel(self)
        self.gSLabel.setObjectName("gSLabel")
        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.gSLabel)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_4 = QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.sensiLabel = QLabel(self)
        self.sensiLabel.setObjectName("sensiLabel")
        self.formLayout_4.setWidget(1, QFormLayout.LabelRole, self.sensiLabel)
        self.sensiTextEdit = QTextEdit(self)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensiTextEdit.sizePolicy().hasHeightForWidth())
        self.sensiTextEdit.setSizePolicy(sizePolicy)
        self.sensiTextEdit.setObjectName("sensiTextEdit")
        self.formLayout_4.setWidget(1, QFormLayout.FieldRole, self.sensiTextEdit)
        self.horizontalLayout_2.addLayout(self.formLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QLabel(self)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_6 = QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.cALabel = QLabel(self)
        self.cALabel.setObjectName("cALabel")
        self.formLayout_6.setWidget(0, QFormLayout.LabelRole, self.cALabel)
        self.cALineEdit = QLineEdit(self)
        self.cALineEdit.setObjectName("cALineEdit")
        self.formLayout_6.setWidget(0, QFormLayout.FieldRole, self.cALineEdit)
        self.immunitLabel = QLabel(self)
        self.immunitLabel.setObjectName("immunitLabel")
        self.formLayout_6.setWidget(1, QFormLayout.LabelRole, self.immunitLabel)
        self.immunitLineEdit = QLineEdit(self)
        self.immunitLineEdit.setObjectName("immunitLineEdit")
        self.formLayout_6.setWidget(1, QFormLayout.FieldRole, self.immunitLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayout_6)
        self.formLayout_5 = QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.pFLabel = QLabel(self)
        self.pFLabel.setObjectName("pFLabel")
        self.formLayout_5.setWidget(0, QFormLayout.LabelRole, self.pFLabel)
        self.pFLineEdit = QLineEdit(self)
        self.pFLineEdit.setObjectName("pFLineEdit")
        self.formLayout_5.setWidget(0, QFormLayout.FieldRole, self.pFLineEdit)
        self.capacitDifensiveLabel = QLabel(self)
        self.capacitDifensiveLabel.setObjectName("capacitDifensiveLabel")
        self.formLayout_5.setWidget(1, QFormLayout.LabelRole, self.capacitDifensiveLabel)
        self.capacitDifensiveLineEdit = QLineEdit(self)
        self.capacitDifensiveLineEdit.setObjectName("capacitDifensiveLineEdit")
        self.formLayout_5.setWidget(1, QFormLayout.FieldRole, self.capacitDifensiveLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayout_5)
        self.formLayout_7 = QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.tiriSalvezzaLabel = QLabel(self)
        self.tiriSalvezzaLabel.setObjectName("tiriSalvezzaLabel")
        self.formLayout_7.setWidget(0, QFormLayout.LabelRole, self.tiriSalvezzaLabel)
        self.tiriSalvezzaLineEdit = QLineEdit(self)
        self.tiriSalvezzaLineEdit.setObjectName("tiriSalvezzaLineEdit")
        self.formLayout_7.setWidget(0, QFormLayout.FieldRole, self.tiriSalvezzaLineEdit)
        self.debolezzeLabel = QLabel(self)
        self.debolezzeLabel.setObjectName("debolezzeLabel")
        self.formLayout_7.setWidget(1, QFormLayout.LabelRole, self.debolezzeLabel)
        self.debolezzeLineEdit = QLineEdit(self)
        self.debolezzeLineEdit.setObjectName("debolezzeLineEdit")
        self.formLayout_7.setWidget(1, QFormLayout.FieldRole, self.debolezzeLineEdit)
        self.horizontalLayout_3.addLayout(self.formLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_2 = QLabel(self)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_11 = QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.velocitLabel = QLabel(self)
        self.velocitLabel.setObjectName("velocitLabel")
        self.formLayout_11.setWidget(0, QFormLayout.LabelRole, self.velocitLabel)
        self.velocitLineEdit = QLineEdit(self)
        self.velocitLineEdit.setObjectName("velocitLineEdit")
        self.formLayout_11.setWidget(0, QFormLayout.FieldRole, self.velocitLineEdit)
        self.atkSpecialiLabel = QLabel(self)
        self.atkSpecialiLabel.setObjectName("atkSpecialiLabel")
        self.formLayout_11.setWidget(1, QFormLayout.LabelRole, self.atkSpecialiLabel)
        self.atkSpecialiLineEdit = QLineEdit(self)
        self.atkSpecialiLineEdit.setObjectName("atkSpecialiLineEdit")
        self.formLayout_11.setWidget(1, QFormLayout.FieldRole, self.atkSpecialiLineEdit)
        self.horizontalLayout_4.addLayout(self.formLayout_11)
        self.formLayout_10 = QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.atkMischiaLabel = QLabel(self)
        self.atkMischiaLabel.setObjectName("atkMischiaLabel")
        self.formLayout_10.setWidget(0, QFormLayout.LabelRole, self.atkMischiaLabel)
        self.atkMischiaLineEdit = QLineEdit(self)
        self.atkMischiaLineEdit.setObjectName("atkMischiaLineEdit")
        self.formLayout_10.setWidget(0, QFormLayout.FieldRole, self.atkMischiaLineEdit)
        self.spazioLabel = QLabel(self)
        self.spazioLabel.setObjectName("spazioLabel")
        self.formLayout_10.setWidget(1, QFormLayout.LabelRole, self.spazioLabel)
        self.spazioLineEdit = QLineEdit(self)
        self.spazioLineEdit.setObjectName("spazioLineEdit")
        self.formLayout_10.setWidget(1, QFormLayout.FieldRole, self.spazioLineEdit)
        self.horizontalLayout_4.addLayout(self.formLayout_10)
        self.formLayout_9 = QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.atkDistanzaLabel = QLabel(self)
        self.atkDistanzaLabel.setObjectName("atkDistanzaLabel")
        self.formLayout_9.setWidget(0, QFormLayout.LabelRole, self.atkDistanzaLabel)
        self.atkDistanzaLineEdit = QLineEdit(self)
        self.atkDistanzaLineEdit.setObjectName("atkDistanzaLineEdit")
        self.formLayout_9.setWidget(0, QFormLayout.FieldRole, self.atkDistanzaLineEdit)
        self.portataLabel = QLabel(self)
        self.portataLabel.setObjectName("portataLabel")
        self.formLayout_9.setWidget(1, QFormLayout.LabelRole, self.portataLabel)
        self.portataLineEdit = QLineEdit(self)
        self.portataLineEdit.setObjectName("portataLineEdit")
        self.formLayout_9.setWidget(1, QFormLayout.FieldRole, self.portataLineEdit)
        self.horizontalLayout_4.addLayout(self.formLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QLabel(self)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_15 = QFormLayout()
        self.formLayout_15.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_15.setObjectName("formLayout_15")
        self.caratteristicheLabel = QLabel(self)
        self.caratteristicheLabel.setObjectName("caratteristicheLabel")
        self.formLayout_15.setWidget(0, QFormLayout.LabelRole, self.caratteristicheLabel)
        self.caratteristicheLineEdit = QLineEdit(self)
        self.caratteristicheLineEdit.setObjectName("caratteristicheLineEdit")
        self.formLayout_15.setWidget(0, QFormLayout.FieldRole, self.caratteristicheLineEdit)
        self.bMCLabel = QLabel(self)
        self.bMCLabel.setObjectName("bMCLabel")
        self.formLayout_15.setWidget(1, QFormLayout.LabelRole, self.bMCLabel)
        self.bMCLineEdit = QLineEdit(self)
        self.bMCLineEdit.setObjectName("bMCLineEdit")
        self.formLayout_15.setWidget(1, QFormLayout.FieldRole, self.bMCLineEdit)
        self.talentiLabel = QLabel(self)
        self.talentiLabel.setObjectName("talentiLabel")
        self.formLayout_15.setWidget(2, QFormLayout.LabelRole, self.talentiLabel)
        self.talentiLineEdit = QLineEdit(self)
        self.talentiLineEdit.setObjectName("talentiLineEdit")
        self.formLayout_15.setWidget(2, QFormLayout.FieldRole, self.talentiLineEdit)
        self.linguaggiLabel = QLabel(self)
        self.linguaggiLabel.setObjectName("linguaggiLabel")
        self.formLayout_15.setWidget(3, QFormLayout.LabelRole, self.linguaggiLabel)
        self.linguaggiLineEdit = QLineEdit(self)
        self.linguaggiLineEdit.setObjectName("linguaggiLineEdit")
        self.formLayout_15.setWidget(3, QFormLayout.FieldRole, self.linguaggiLineEdit)
        self.descrizioneLabel = QLabel(self)
        self.descrizioneLabel.setObjectName("descrizioneLabel")
        self.formLayout_15.setWidget(4, QFormLayout.LabelRole, self.descrizioneLabel)
        self.textEdit = QTextEdit(self)
        self.textEdit.setObjectName("textEdit")
        self.formLayout_15.setWidget(4, QFormLayout.FieldRole, self.textEdit)
        self.horizontalLayout.addLayout(self.formLayout_15)
        self.formLayout_14 = QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.aBLabel = QLabel(self)
        self.aBLabel.setObjectName("aBLabel")
        self.formLayout_14.setWidget(0, QFormLayout.LabelRole, self.aBLabel)
        self.aBLineEdit = QLineEdit(self)
        self.aBLineEdit.setObjectName("aBLineEdit")
        self.formLayout_14.setWidget(0, QFormLayout.FieldRole, self.aBLineEdit)
        self.dMCLabel = QLabel(self)
        self.dMCLabel.setObjectName("dMCLabel")
        self.formLayout_14.setWidget(1, QFormLayout.LabelRole, self.dMCLabel)
        self.dMCLineEdit = QLineEdit(self)
        self.dMCLineEdit.setObjectName("dMCLineEdit")
        self.formLayout_14.setWidget(1, QFormLayout.FieldRole, self.dMCLineEdit)
        self.abilitLabel = QLabel(self)
        self.abilitLabel.setObjectName("abilitLabel")
        self.formLayout_14.setWidget(2, QFormLayout.LabelRole, self.abilitLabel)
        self.abilitLineEdit = QLineEdit(self)
        self.abilitLineEdit.setObjectName("abilitLineEdit")
        self.formLayout_14.setWidget(2, QFormLayout.FieldRole, self.abilitLineEdit)
        self.ambienteLabel = QLabel(self)
        self.ambienteLabel.setObjectName("ambienteLabel")
        self.formLayout_14.setWidget(3, QFormLayout.LabelRole, self.ambienteLabel)
        self.ambienteLineEdit = QLineEdit(self)
        self.ambienteLineEdit.setObjectName("ambienteLineEdit")
        self.formLayout_14.setWidget(3, QFormLayout.FieldRole, self.ambienteLineEdit)
        self.capacitSpecialilineEdit = QLineEdit(self)
        self.capacitSpecialilineEdit.setObjectName("capacitSpecialilineEdit")
        self.formLayout_14.setWidget(4, QFormLayout.FieldRole, self.capacitSpecialilineEdit)
        self.capacitSpecialiButton = QPushButton(self)
        self.capacitSpecialiButton.setObjectName("capacitSpecialiButton")
        self.formLayout_14.setWidget(4, QFormLayout.LabelRole, self.capacitSpecialiButton)
        self.incantesimiLineEdit = QLineEdit(self)
        self.incantesimiLineEdit.setObjectName("incantesimiLineEdit")
        self.formLayout_14.setWidget(5, QFormLayout.FieldRole, self.incantesimiLineEdit)
        self.incantesimiButton = QPushButton(self)
        self.incantesimiButton.setObjectName("incantesimiButton")
        self.formLayout_14.setWidget(5, QFormLayout.LabelRole, self.incantesimiButton)
        self.horizontalLayout.addLayout(self.formLayout_14)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imgPushButton = QPushButton(self)
        self.imgPushButton.setObjectName("imgPushButton")
        self.horizontalLayout_5.addWidget(self.imgPushButton)
        self.imgLabel = QLabel(self)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout_5.addWidget(self.imgLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.iconPushButton = QPushButton(self)
        self.iconPushButton.setObjectName("iconPushButton")
        self.horizontalLayout_6.addWidget(self.iconPushButton)
        self.iconLabel = QLabel(self)
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_6.addWidget(self.iconLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.nomeLabel.setText("Nome")
        self.iniziativaLabel.setText("Iniziativa")
        self.pELabel.setText("PE")
        self.tesoroButton.setText("Tesoro")
        self.tesoroLineEdit.setReadOnly(True)
        self.categoriaLabel.setText("Categoria")
        self.auraLabel.setText("Aura")
        self.allineamentoLabel.setText("Allineamento")
        self.gSLabel.setText("GS")
        self.sensiLabel.setText("Sensi")
        self.label.setText("<html><head/><body><p><br/><span style=\" font-size:12pt; font-weight:600;\">DIFESA</span></p></body></html>")
        self.cALabel.setText("CA")
        self.immunitLabel.setText("Immunità")
        self.pFLabel.setText("PF")
        self.capacitDifensiveLabel.setText("Capacità Difensive")
        self.tiriSalvezzaLabel.setText("Tiri Salvezza")
        self.debolezzeLabel.setText("Debolezze")
        self.label_2.setText("<html><head/><body><p><br/><span style=\" font-size:12pt; font-weight:600;\">ATTACCO</span></p></body></html>")
        self.velocitLabel.setText("Velocità")
        self.atkSpecialiLabel.setText("Atk Speciali")
        self.atkMischiaLabel.setText("Atk Mischia")
        self.spazioLabel.setText("Spazio")
        self.atkDistanzaLabel.setText("Atk Distanza")
        self.portataLabel.setText("Portata")
        self.label_3.setText("<html><head/><body><p><br/><span style=\" font-size:12pt; font-weight:600;\">STATISTICHE</span></p></body></html>")
        self.caratteristicheLabel.setText("Caratteristiche")
        self.bMCLabel.setText("BMC")
        self.talentiLabel.setText("Talenti")
        self.linguaggiLabel.setText("Linguaggi")
        self.descrizioneLabel.setText("Descrizione")
        self.aBLabel.setText("AB")
        self.dMCLabel.setText("DMC")
        self.abilitLabel.setText("Abilità")
        self.ambienteLabel.setText("Ambiente")
        self.capacitSpecialiButton.setText("Capacità Speciali")
        self.capacitSpecialilineEdit.setReadOnly(True)
        self.incantesimiButton.setText("Incantesimi")
        self.incantesimiLineEdit.setReadOnly(True)
        self.imgPushButton.setText("Immagine")
        self.iconPushButton.setText("Icona")


def main(args):
    app = QApplication(args)
    #db = DB_Manager('test.db')
    window = QMainWindow()
    frame = Frame_New_Monster(window)
    window.setCentralWidget(frame)
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main(sys.argv)
