# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Incantesimi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
#
#
# APPROVED!!!!!!!!!!!!!!!

from PyQt4 import QtCore, QtGui

from PyQt4.QtGui import *
from DatabaseFinal.DBManager import *
from Frames.Frame_Spells import *

class Frame_New_Spell(QFrame):
    def __init__(self, db, parent=None):
        super(Frame_New_Spell, self).__init__(parent)
        self.parent = parent
        self.db = db
        self.setObjectName("Frame_Incantesimi")
        self.resize(857, 464)
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName(("verticalLayout"))
        self.label = QLabel(self)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nomeLabel = QLabel(self)
        self.nomeLabel.setObjectName("nomeLabel")
        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.nomeLabel)
        self.nomeLineEdit = QLineEdit(self)
        self.nomeLineEdit.setObjectName("nomeLineEdit")
        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.nomeLineEdit)
        self.livelloLabel = QLabel(self)
        self.livelloLabel.setObjectName("livelloLabel")
        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.livelloLabel)
        self.livelloComboBox = QComboBox(self)
        self.livelloComboBox.setObjectName("livelloComboBox")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.livelloComboBox.addItem("")
        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.livelloComboBox)
        self.raggioDiAzioneLabel = QLabel(self)
        self.raggioDiAzioneLabel.setObjectName("raggioDiAzioneLabel")
        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.raggioDiAzioneLabel)
        self.raggioDiAzioneLineEdit = QLineEdit(self)
        self.raggioDiAzioneLineEdit.setObjectName("raggioDiAzioneLineEdit")
        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.raggioDiAzioneLineEdit)
        self.tiroSalvezzaLabel = QLabel(self)
        self.tiroSalvezzaLabel.setObjectName("tiroSalvezzaLabel")
        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.tiroSalvezzaLabel)
        self.tiroSalvezzaLineEdit = QLineEdit(self)
        self.tiroSalvezzaLineEdit.setObjectName("tiroSalvezzaLineEdit")
        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.tiroSalvezzaLineEdit)
        self.descrizioneLabel = QLabel(self)
        self.descrizioneLabel.setObjectName("descrizioneLabel")
        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.descrizioneLabel)
        self.textEditDescrizione = QTextEdit(self)
        self.textEditDescrizione.setObjectName("textEditDescrizione")
        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.textEditDescrizione)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout = QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.scuolaLabel = QLabel(self)
        self.scuolaLabel.setObjectName("scuolaLabel")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.scuolaLabel)
        self.scuolaComboBox = QComboBox(self)
        self.scuolaComboBox.setObjectName("scuolaComboBox")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.scuolaComboBox.addItem("")
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.scuolaComboBox)
        self.classeLabel = QLabel(self)
        self.classeLabel.setObjectName("classeLabel")
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.classeLabel)
        self.classeComboBox = QComboBox(self)
        self.classeComboBox.setObjectName("classeComboBox")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.classeComboBox.addItem("")
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.classeComboBox)
        self.tempoDiLancioLabel = QLabel(self)
        self.tempoDiLancioLabel.setObjectName("tempoDiLancioLabel")
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.tempoDiLancioLabel)
        self.tempoDiLancioLineEdit = QLineEdit(self)
        self.tempoDiLancioLineEdit.setObjectName("tempoDiLancioLineEdit")
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.tempoDiLancioLineEdit)
        self.durataLabel = QLabel(self)
        self.durataLabel.setObjectName("durataLabel")
        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.durataLabel)
        self.durataLineEdit = QLineEdit(self)
        self.durataLineEdit.setObjectName("durataLineEdit")
        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.durataLineEdit)
        self.bersaglioLabel = QLabel(self)
        self.bersaglioLabel.setObjectName("bersaglioLabel")
        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.bersaglioLabel)
        self.bersaglioLineEdit = QLineEdit(self)
        self.bersaglioLineEdit.setObjectName("bersaglioLineEdit")
        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.bersaglioLineEdit)
        self.resistenzaAgliIncantesimiLabel_2 = QLabel(self)
        self.resistenzaAgliIncantesimiLabel_2.setObjectName("resistenzaAgliIncantesimiLabel_2")
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.resistenzaAgliIncantesimiLabel_2)
        self.resistenzaAgliIncantesimiComboBox = QComboBox(self)
        self.resistenzaAgliIncantesimiComboBox.setObjectName("resistenzaAgliIncantesimiComboBox")
        self.resistenzaAgliIncantesimiComboBox.addItem("")
        self.resistenzaAgliIncantesimiComboBox.addItem("")
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.resistenzaAgliIncantesimiComboBox)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QLabel(self)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxFocusDivina = QCheckBox(self)
        self.checkBoxFocusDivina.setObjectName("checkBoxFocusDivina")
        self.horizontalLayout_2.addWidget(self.checkBoxFocusDivina)
        self.checkBoxFocus = QCheckBox(self)
        self.checkBoxFocus.setObjectName("checkBoxFocus")
        self.horizontalLayout_2.addWidget(self.checkBoxFocus)
        self.checkBoxMateriale = QCheckBox(self)
        self.checkBoxMateriale.setObjectName("checkBoxMateriale")
        self.horizontalLayout_2.addWidget(self.checkBoxMateriale)
        self.checkBoxSomatica = QCheckBox(self)
        self.checkBoxSomatica.setObjectName("checkBoxSomatica")
        self.horizontalLayout_2.addWidget(self.checkBoxSomatica)
        self.checkBoxVerbale = QCheckBox(self)
        self.checkBoxVerbale.setObjectName("checkBoxVerbale")
        self.horizontalLayout_2.addWidget(self.checkBoxVerbale)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.hButtonLayout = QHBoxLayout()
        self.buttonOk = QPushButton(self)
        self.buttonCancel = QPushButton("Cancel")
        self.hButtonLayout.addWidget(self.buttonOk)
        self.hButtonLayout.addWidget(self.buttonCancel)
        self.verticalLayout.addLayout(self.hButtonLayout)

        self.setWindowTitle("Nuova Spell")
        self.label.setText("<html><head/><body><p><br/><span style=\" font-size:12pt; font-weight:600;\">INCANTESIMO</span></p></body></html>")
        self.nomeLabel.setText("Nome")
        self.livelloLabel.setText("Livello")
        self.livelloComboBox.setItemText(0, "1")
        self.livelloComboBox.setItemText(1, "2")
        self.livelloComboBox.setItemText(2, "3")
        self.livelloComboBox.setItemText(3, "4")
        self.livelloComboBox.setItemText(4, "5")
        self.livelloComboBox.setItemText(5, "6")
        self.livelloComboBox.setItemText(6, "7")
        self.livelloComboBox.setItemText(7, "8")
        self.livelloComboBox.setItemText(8, "9")
        self.livelloComboBox.setItemText(9, "10")
        self.livelloComboBox.setItemText(10, "11")
        self.livelloComboBox.setItemText(11, "12")
        self.livelloComboBox.setItemText(12, "13")
        self.livelloComboBox.setItemText(13, "14")
        self.livelloComboBox.setItemText(14, "15")
        self.livelloComboBox.setItemText(15, "16")
        self.livelloComboBox.setItemText(16, "17")
        self.livelloComboBox.setItemText(17, "18")
        self.livelloComboBox.setItemText(18, "19")
        self.livelloComboBox.setItemText(19, "20")
        self.raggioDiAzioneLabel.setText("Raggio di azione")
        self.tiroSalvezzaLabel.setText("Tiro Salvezza")
        self.descrizioneLabel.setText("Descrizione")
        self.scuolaLabel.setText("Scuola")
        self.scuolaComboBox.setItemText(0, "Abiurazione")
        self.scuolaComboBox.setItemText(1, "Ammaliamento")
        self.scuolaComboBox.setItemText(2, "Divinazione")
        self.scuolaComboBox.setItemText(3, "Evocazione")
        self.scuolaComboBox.setItemText(4, "Illusione")
        self.scuolaComboBox.setItemText(5, "Invocazione")
        self.scuolaComboBox.setItemText(6, "Trasmutazione")
        self.classeLabel.setText("Classe")
        self.classeComboBox.setItemText(0, "Mago")
        self.classeComboBox.setItemText(1, "Stregone")
        self.classeComboBox.setItemText(2, "Bardo")
        self.classeComboBox.setItemText(3, "Druido")
        self.classeComboBox.setItemText(4, "Chierico")
        self.classeComboBox.setItemText(5, "Paladino")
        self.classeComboBox.setItemText(6, "Monaco")
        self.classeComboBox.setItemText(7, "Renger")
        self.classeComboBox.setItemText(8, "Ladro")
        self.classeComboBox.setItemText(9, "Guerriero")
        self.classeComboBox.setItemText(10, "Barbaro")
        self.tempoDiLancioLabel.setText("Tempo di lancio")
        self.durataLabel.setText("Durata")
        self.bersaglioLabel.setText("Bersaglio")
        self.resistenzaAgliIncantesimiLabel_2.setText("Resistenza agli incantesimi")
        self.resistenzaAgliIncantesimiComboBox.setItemText(0, "no")
        self.resistenzaAgliIncantesimiComboBox.setItemText(1, "si")
        self.label_2.setText("<html><head/><body><p><br/><span style=\" font-size:10pt; font-weight:600;\">Componenti</span></p></body></html>")
        self.checkBoxFocusDivina.setText("Focus Divina")
        self.checkBoxFocus.setText("Focus")
        self.checkBoxMateriale.setText("Materiale")
        self.checkBoxSomatica.setText("Somatica")
        self.checkBoxVerbale.setText("Verbale")
        self.buttonOk.setText("OK")
        self.buttonOk.clicked.connect(self.eventButtonOk)


    def eventButtonOk(self):
        if isinstance(self.db, DB_Manager):
            nome = self.nomeLineEdit.text()
            scuola = self.scuolaComboBox.currentText()
            livello = self.livelloComboBox.currentText()
            classe = self.classeComboBox.currentText()
            raggioAzione = self.raggioDiAzioneLineEdit.text()
            res_inc = self.resistenzaAgliIncantesimiComboBox.currentText()
            tiro_salvezza = self.tiroSalvezzaLineEdit.text()
            tempo_di_lancio = self.tempoDiLancioLineEdit.text()
            descrizione = self.textEditDescrizione.toPlainText()
            durata = self.durataLineEdit.text()
            bersaglio = self.bersaglioLineEdit.text()
            componenti = ""
            if(self.checkBoxFocusDivina.isChecked()):
                componenti += self.checkBoxFocusDivina.text() +"; "
            if(self.checkBoxFocus.isChecked()):
                componenti += self.checkBoxFocus.text() +"; "
            if(self.checkBoxMateriale.isChecked()):
                componenti += self.checkBoxMateriale.text() +"; "
            if(self.checkBoxSomatica.isChecked()):
                componenti += self.checkBoxSomatica.text() +"; "
            if(self.checkBoxVerbale.isChecked()):
                componenti += self.checkBoxVerbale.text() +";"
            '''Verifica se i campi sono compilati'''
            if(nome and scuola and livello and classe and raggioAzione and res_inc and tiro_salvezza and tempo_di_lancio and
               descrizione and durata and bersaglio):
                spell = Spell(nome, scuola, livello, classe, raggioAzione, res_inc, tiro_salvezza, tempo_di_lancio, descrizione, durata, bersaglio, componenti)
                result = self.db.insertSpell(spell)
                if(result):
                    msg = QMessageBox()
                    msg.setWindowTitle("Nuova Spell")
                    msg.setText("Spell inserita correttamente")
                    msg.exec_()
                else:
                    msg = QMessageBox()
                    msg.setWindowTitle("Nuova Spell")
                    msg.setText("Esiste già una spell con lo stesso nome")
                    msg.exec_()
            else:
                msg = QMessageBox()
                msg.setWindowTitle("Nuova Spell")
                msg.setText("Si prega di non lasciare campi vuoti")
                msg.exec_()

    '''
    def eventButtonCancel(self):
        self.returnToFrameSpells()

    def returnToFrameSpells(self):
        if (isinstance(self.parent, QMainWindow)):
            frame = FrameSpells(self.db, self.parent)
            self.parent.setCentralWidget(frame)
    '''
'''
class Test():
    app = QApplication(sys.argv)

    db = DB_Manager("test.db")

    frameNewSpell = Frame_New_Spell(db)
    frameNewSpell.show()

    sys.exit(app.exec_())


if __name__ == '__main__':
    Test()
'''